nav:
  - component: HTML
    args:
      html: <strong>Make everything 30'</strong>
  - <strong><a href="https://eleme.github.io/duang/docs/" target="_blank">Duang</a></strong>
  - component: User
schemes:
  - schemes/inputs/datetime.json
  - schemes/inputs/keyboards.json
  - schemes/inputs/clicking.json
  - schemes/inputs/grouping.json
  - schemes/inputs/other.json
  - schemes/inputs/combines.json
  - schemes/inputs/caption.json
  - schemes/config/list.yaml
  - schemes/config/filter.yaml
  - schemes/config/error.yaml
  - schemes/config/form.yaml
  - schemes/config/hidden.yaml
  - key: doc
    title: 文档
    module: Custom
    params:
      href: 'https://eleme.github.io/duang/docs/'
logo: Duang Demo
session:
  authorize: authorize.json
  method: get
